const LEAGUES = {
  'tur.1': { name: 'Süper Lig', country: 'Türkiye', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/5.png' },
  'eng.1': { name: 'Premier Lig', country: 'İngiltere', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/23.png' },
  'esp.1': { name: 'La Liga', country: 'İspanya', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/15.png' },
  'ita.1': { name: 'Serie A', country: 'İtalya', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/12.png' },
  'ger.1': { name: 'Bundesliga', country: 'Almanya', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/10.png' },
  'fra.1': { name: 'Ligue 1', country: 'Fransa', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/9.png' },
  'ned.1': { name: 'Eredivisie', country: 'Hollanda', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/18.png' },
  'por.1': { name: 'Liga Portugal', country: 'Portekiz', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/20.png' },
  'sco.1': { name: 'Scottish Premiership', country: 'İskoçya', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/22.png' },
  'bel.1': { name: 'Pro League', country: 'Belçika', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/7.png' },
  'mex.1': { name: 'Liga MX', country: 'Meksika', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/27.png' },
  'usa.1': { name: 'MLS', country: 'ABD', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/31.png' },
  'bra.1': { name: 'Brasileirão', country: 'Brezilya', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/28.png' },
  'arg.1': { name: 'Liga Profesional', country: 'Arjantin', logo: 'https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/29.png' },
  'chn.1': { name: 'Çin Süper Ligi', country: 'Çin', logo: '' },
  'jpn.1': { name: 'J1 League', country: 'Japonya', logo: '' },
  'sau.1': { name: 'Saudi Pro League', country: 'Suudi Arabistan', logo: '' },
  'swe.1': { name: 'Allsvenskan', country: 'İsveç', logo: '' },
  'nor.1': { name: 'Eliteserien', country: 'Norveç', logo: '' },
  'aut.1': { name: 'Bundesliga', country: 'Avusturya', logo: '' },
  'sui.1': { name: 'Super League', country: 'İsviçre', logo: '' },
  'gre.1': { name: 'Super League', country: 'Yunanistan', logo: '' },
  'cro.1': { name: 'HNL', country: 'Hırvatistan', logo: '' },
  'cze.1': { name: 'First League', country: 'Çekya', logo: '' },
  'den.1': { name: 'Superliga', country: 'Danimarka', logo: '' },
  'ukr.1': { name: 'Premier League', country: 'Ukrayna', logo: '' },
  'rus.1': { name: 'Premier League', country: 'Rusya', logo: '' },
  'pol.1': { name: 'Ekstraklasa', country: 'Polonya', logo: '' },
  'rou.1': { name: 'Liga I', country: 'Romanya', logo: '' },
  'bul.1': { name: 'First League', country: 'Bulgaristan', logo: '' },
  'srb.1': { name: 'Super Liga', country: 'Sırbistan', logo: '' },
  'tur.2': { name: 'TFF 1. Lig', country: 'Türkiye', logo: '' },
  'eng.2': { name: 'EFL Championship', country: 'İngiltere', logo: '' },
  'esp.2': { name: 'La Liga 2', country: 'İspanya', logo: '' },
  'ita.2': { name: 'Serie B', country: 'İtalya', logo: '' },
  'ger.2': { name: '2. Bundesliga', country: 'Almanya', logo: '' },
  'fra.2': { name: 'Ligue 2', country: 'Fransa', logo: '' },
  'ned.2': { name: 'Eerste Divisie', country: 'Hollanda', logo: '' },
  'sco.2': { name: 'Scottish Championship', country: 'İskoçya', logo: '' },
  'mex.2': { name: 'Liga de Expansión', country: 'Meksika', logo: '' },
  'bra.2': { name: 'Brasileirão Série B', country: 'Brezilya', logo: '' },
  'arg.2': { name: 'Primera Nacional', country: 'Arjantin', logo: '' },
  'por.2': { name: 'Liga Portugal 2', country: 'Portekiz', logo: '', source: 'flashscore' },
  'bel.2': { name: 'Challenger Pro League', country: 'Belçika', logo: '', source: 'flashscore' },
  'gre.2': { name: 'Super League 2', country: 'Yunanistan', logo: '', source: 'flashscore' },
  'cro.2': { name: 'Prva NL', country: 'Hırvatistan', logo: '', source: 'flashscore' },
  'cze.2': { name: 'FNL', country: 'Çekya', logo: '', source: 'flashscore' },
  'ukr.2': { name: 'Persha Liha', country: 'Ukrayna', logo: '', source: 'flashscore' },
  'rus.2': { name: 'FNL', country: 'Rusya', logo: '', source: 'flashscore' },
  'pol.2': { name: 'I Liga', country: 'Polonya', logo: '', source: 'flashscore' },
  'rou.2': { name: 'Liga II', country: 'Romanya', logo: '', source: 'flashscore' },
  'bul.2': { name: 'Second League', country: 'Bulgaristan', logo: '', source: 'flashscore' },
  'srb.2': { name: 'Prva Liga', country: 'Sırbistan', logo: '', source: 'flashscore' },
  'chn.2': { name: 'China League One', country: 'Çin', logo: '', source: 'flashscore' },
  'jpn.2': { name: 'J2 League', country: 'Japonya', logo: '', source: 'flashscore' },
  'sau.2': { name: 'First Division', country: 'Suudi Arabistan', logo: '', source: 'flashscore' },
  'swe.2': { name: 'Superettan', country: 'İsveç', logo: '', source: 'flashscore' },
  'nor.2': { name: 'OBOS-ligaen', country: 'Norveç', logo: '', source: 'flashscore' },
  'aut.2': { name: '2. Liga', country: 'Avusturya', logo: '', source: 'flashscore' },
  'sui.2': { name: 'Challenge League', country: 'İsviçre', logo: '', source: 'flashscore' },
  'den.2': { name: '1. Division', country: 'Danimarka', logo: '', source: 'flashscore' },
  'fin.1': { name: 'Veikkausliiga', country: 'Finlandiya', logo: '', source: 'flashscore' },
  'fin.2': { name: 'Ykkonen', country: 'Finlandiya', logo: '', source: 'flashscore' },
  'blr.1': { name: 'Premier Ligi', country: 'Belarus', logo: '', source: 'flashscore' },
  'blr.2': { name: 'Pershaya Ligi', country: 'Belarus', logo: '', source: 'flashscore' },
};

const LEAGUE_IDS = Object.keys(LEAGUES);

module.exports = { LEAGUES, LEAGUE_IDS };
